// RETAIL frontend starter. Public/publishable Supabase key is safe to use in a browser; never add service_role keys here.
const SUPABASE_URL = "https://oebapdfkaumpmwdblqbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_wmNek6qB6MCiPIJzueJhVQ_7-6d42yl";
const db = window.supabase?.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const sample=[
 {id:"s1",title:"Everyday Wireless Headphones",category:"Electronics",price:1299,emoji:"🎧",seller:"RETAIL Picks"},
 {id:"s2",title:"Minimal Everyday Backpack",category:"Fashion",price:899,emoji:"🎒",seller:"Urban Lane"},
 {id:"s3",title:"Ceramic Table Lamp",category:"Home",price:749,emoji:"💡",seller:"Home & Living"},
 {id:"s4",title:"Daily Care Essentials Set",category:"Beauty",price:499,emoji:"🧴",seller:"Glow Basket"},
 {id:"s5",title:"Reusable Steel Bottle",category:"Home",price:349,emoji:"🥤",seller:"Earth Goods"},
 {id:"s6",title:"Classic Cotton T-shirt",category:"Fashion",price:599,emoji:"👕",seller:"Thread House"},
 {id:"s7",title:"Desk Organizer",category:"Other",price:279,emoji:"🗂️",seller:"WorkNest"},
 {id:"s8",title:"Snack & Pantry Box",category:"Grocery",price:399,emoji:"🛒",seller:"Daily Basket"}
];
let products=[...sample],cart=[],active="All";
const $=id=>document.getElementById(id), money=n=>"₹"+Number(n).toLocaleString("en-IN");
function draw(){let q=$("search").value.trim().toLowerCase();let shown=products.filter(p=>(active==="All"||p.category===active)&&(!q||p.title.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)));$("resultCount").textContent=`${shown.length} items`; $("products").innerHTML=shown.map(p=>`<article class="product"><div class="photo">${p.image_url?`<img src="${p.image_url}" alt="" style="width:100%;height:100%;object-fit:cover">`:p.emoji||"📦"}</div><div class="pbody"><div class="tag">${p.category||"Discover"}</div><h3>${escapeHtml(p.title)}</h3><div class="price">${money(p.price)}</div><div class="seller">Sold by ${escapeHtml(p.seller_name||p.seller||"Marketplace seller")}</div><div class="actions"><button class="add" data-add="${p.id}">Add to cart</button><button class="buy" data-buy="${p.id}">Buy Now</button></div></div></article>`).join("")||'<p>No products found. Try another search.</p>';document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{let p=products.find(x=>String(x.id)===b.dataset.add);cart.push(p);$("cartCount").textContent=cart.length;b.textContent="Added ✓";setTimeout(()=>b.textContent="Add to cart",900)});document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{let p=products.find(x=>String(x.id)===b.dataset.buy);buyNow(p)})}
function buyNow(p){modal(`<h2>Buy Now</h2><div class="lineitem"><span>${escapeHtml(p.title)}</span><b>${money(p.price)}</b></div><p class="notice"><b>Cash on Delivery only.</b></p><label>Name</label><input id="buyName" placeholder="Your name"><label>Mobile</label><input id="buyMobile" inputmode="tel" placeholder="10-digit mobile"><label>Delivery address</label><textarea id="buyAddress" placeholder="Full address"></textarea><button class="primary" id="buyConfirm" type="button">Place COD Order</button><p id="buyMsg"></p>`);$("buyConfirm").onclick=()=>{let m=$("buyMsg"),n=$("buyName").value.trim(),ph=$("buyMobile").value.trim(),a=$("buyAddress").value.trim();if(!n||!/^\\d{10}$/.test(ph)||!a){m.textContent="Enter valid name, 10-digit mobile and address.";return}m.textContent="COD order details saved. Login is required for final order placement."}}\nfunction escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function modal(html){$("modalBody").innerHTML=html;$("modal").showModal()}
async function loadLive(){if(!db)return;try{const {data,error}=await db.from("products").select("id,title,description,price,image_url,category_id").eq("status","active").order("created_at",{ascending:false}).limit(60);if(error)throw error;if(data?.length)products=data.map(p=>({...p,category:"Other",seller_name:"Verified seller"}));draw()}catch(e){console.info("Using starter catalogue until live product categories are configured.",e.message)}}
$("searchBtn").onclick=draw;$("search").oninput=draw;$("shopNow").onclick=()=>$("products").scrollIntoView({behavior:"smooth"});$("cats").onclick=e=>{let b=e.target.closest("button[data-cat]");if(!b)return;active=b.dataset.cat;document.querySelectorAll(".cats button").forEach(x=>x.classList.toggle("selected",x===b));draw()};
$("loginBtn").onclick=()=>modal(`<h2>Welcome to RETAIL</h2><p class="notice">Customer sign-in is being connected. You can preview the storefront and cart now.</p><label>Email</label><input type="email" placeholder="you@example.com" id="email"><label>Password</label><input type="password" placeholder="At least 6 characters" id="password"><button class="primary" id="authAction" type="button">Sign in / Create account</button><p id="authMsg"></p>`); 
$("modal").addEventListener("click",async e=>{if(e.target.id==="authAction"){let email=$("email").value,password=$("password").value;let msg=$("authMsg");if(!email||!password){msg.textContent="Enter email and password.";return}if(!db){msg.textContent="Backend unavailable.";return}let {data,error}=await db.auth.signInWithPassword({email,password});if(error){let r=await db.auth.signUp({email,password});error=r.error;data=r.data}msg.textContent=error?error.message:"Account action completed. Check your email if verification is required."}});
$("cartBtn").onclick=()=>{if(!cart.length){modal("<h2>Your cart is empty</h2><p>Choose a product to add it here.</p>");return}let total=cart.reduce((s,p)=>s+Number(p.price),0);modal(`<h2>Your cart</h2>${cart.map((p,i)=>`<div class="lineitem"><span>${escapeHtml(p.title)}</span><b>${money(p.price)}</b></div>`).join("")}<div class="lineitem"><b>Subtotal</b><b>${money(total)}</b></div><p class="notice">Checkout and COD order placement will be enabled after the secure order workflow is connected. No payment is collected in this preview.</p>`)}
$("sellerBtn").onclick=()=>modal(`<h2>Sell on RETAIL</h2><p>Seller onboarding is planned with identity and business verification before approval.</p><label>Store name</label><input placeholder="Your shop name"><label>Contact email</label><input type="email" placeholder="seller@example.com"><p class="notice">Seller application submission will be enabled after authenticated seller permissions and admin review are configured.</p>`);
draw();loadLive();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
